In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("datasets_1111_2005_kidney_disease.csv")
dataset


id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent   
1      1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent   
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent   
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present   
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent   
..   ...   ...   ...    ...  ...  ...     ...       ...         ...   
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent   

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no   
1    notpresent  ...   38  6000  NaN   no   no   no  good   no   no   
2    notpresent  ...   31  7500  NaN   no  yes   no  poor   no  yes   
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes   
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no   
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no   
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no   
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no   
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no   
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no   

    classification  
0              ckd  
1              ckd  
2              ckd  
3              ckd  
4              ckd  
..             ...  
395         notckd  
396         notckd  
397         notckd  
398         notckd  
399         notckd  

[400 rows x 26 columns]

In [3]:
dataset.isnull().any()

id                False
age                True
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [4]:
dataset['age'].fillna(dataset['age'].mean(),inplace=True)
dataset['bp'].fillna(dataset['bp'].mean(),inplace=True)
dataset['sg'].fillna(dataset['sg'].mean(),inplace=True)
dataset['al'].fillna(dataset['al'].mean(),inplace=True)
dataset['su'].fillna(dataset['su'].mean(),inplace=True)
dataset['bgr'].fillna(dataset['bgr'].mean(),inplace=True)
dataset['bu'].fillna(dataset['bu'].mean(),inplace=True)
dataset['sc'].fillna(dataset['sc'].mean(),inplace=True)
dataset['sod'].fillna(dataset['sod'].mean(),inplace=True)
dataset['pot'].fillna(dataset['pot'].mean(),inplace=True)
dataset['hemo'].fillna(dataset['hemo'].mean(),inplace=True)


In [5]:
dataset.isnull().any()

id                False
age               False
bp                False
sg                False
al                False
su                False
rbc                True
pc                 True
pcc                True
ba                 True
bgr               False
bu                False
sc                False
sod               False
pot               False
hemo              False
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [6]:
dataset['rbc']=dataset['rbc'].fillna(value=dataset['rbc'].mode().iloc[0])
dataset['pc']=dataset['rbc'].fillna(value=dataset['pc'].mode().iloc[0])
dataset['pcc']=dataset['pcc'].fillna(value=dataset['pcc'].mode().iloc[0])
dataset['ba']=dataset['ba'].fillna(value=dataset['ba'].mode().iloc[0])

In [7]:
dataset['pcv']=dataset['pcv'].fillna(value=dataset['pcv'].mode().iloc[0])
dataset['wc']=dataset['wc'].fillna(value=dataset['wc'].mode().iloc[0])
dataset['rc']=dataset['rc'].fillna(value=dataset['rc'].mode().iloc[0])
dataset['htn']=dataset['htn'].fillna(value=dataset['htn'].mode().iloc[0])
dataset['dm']=dataset['dm'].fillna(value=dataset['dm'].mode().iloc[0])
dataset['cad']=dataset['cad'].fillna(value=dataset['cad'].mode().iloc[0])
dataset['appet']=dataset['appet'].fillna(value=dataset['appet'].mode().iloc[0])
dataset['pe']=dataset['pe'].fillna(value=dataset['pe'].mode().iloc[0])
dataset['ane']=dataset['ane'].fillna(value=dataset['ane'].mode().iloc[0])

In [8]:
dataset

id   age    bp     sg   al   su     rbc      pc         pcc          ba  \
0      0  48.0  80.0  1.020  1.0  0.0  normal  normal  notpresent  notpresent   
1      1   7.0  50.0  1.020  4.0  0.0  normal  normal  notpresent  notpresent   
2      2  62.0  80.0  1.010  2.0  3.0  normal  normal  notpresent  notpresent   
3      3  48.0  70.0  1.005  4.0  0.0  normal  normal     present  notpresent   
4      4  51.0  80.0  1.010  2.0  0.0  normal  normal  notpresent  notpresent   
..   ...   ...   ...    ...  ...  ...     ...     ...         ...         ...   
395  395  55.0  80.0  1.020  0.0  0.0  normal  normal  notpresent  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0  normal  normal  notpresent  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0  normal  normal  notpresent  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0  normal  normal  notpresent  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0  normal  normal  notpresent  notpresent   

     ...  pcv    wc   rc  htn   dm  cad appet   pe  ane classification  
0    ...   44  7800  5.2  yes  yes   no  good   no   no            ckd  
1    ...   38  6000  5.2   no   no   no  good   no   no            ckd  
2    ...   31  7500  5.2   no  yes   no  poor   no  yes            ckd  
3    ...   32  6700  3.9  yes   no   no  poor  yes  yes            ckd  
4    ...   35  7300  4.6   no   no   no  good   no   no            ckd  
..   ...  ...   ...  ...  ...  ...  ...   ...  ...  ...            ...  
395  ...   47  6700  4.9   no   no   no  good   no   no         notckd  
396  ...   54  7800  6.2   no   no   no  good   no   no         notckd  
397  ...   49  6600  5.4   no   no   no  good   no   no         notckd  
398  ...   51  7200  5.9   no   no   no  good   no   no         notckd  
399  ...   53  6800  6.1   no   no   no  good   no   no         notckd  

[400 rows x 26 columns]

In [9]:
dataset.isnull().any()

id                False
age               False
bp                False
sg                False
al                False
su                False
rbc               False
pc                False
pcc               False
ba                False
bgr               False
bu                False
sc                False
sod               False
pot               False
hemo              False
pcv               False
wc                False
rc                False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [10]:
x=dataset.iloc[:,1:25].values
x

array([[48.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [7.0, 50.0, 1.02, ..., 'good', 'no', 'no'],
       [62.0, 80.0, 1.01, ..., 'poor', 'no', 'yes'],
       ...,
       [12.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [17.0, 60.0, 1.025, ..., 'good', 'no', 'no'],
       [58.0, 80.0, 1.025, ..., 'good', 'no', 'no']], dtype=object)

In [11]:
y=dataset.iloc[:,25:].values
y

array([['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd\t'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
      

In [12]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [13]:
x[:,7]=lb.fit_transform(x[:,7])
x[:,8]=lb.fit_transform(x[:,8])
x[:,9]=lb.fit_transform(x[:,9])
x[:,10]=lb.fit_transform(x[:,10])
x[:,18]=lb.fit_transform(x[:,18])
x[:,19]=lb.fit_transform(x[:,19])
x[:,20]=lb.fit_transform(x[:,20])
x[:,21]=lb.fit_transform(x[:,21])
x[:,22]=lb.fit_transform(x[:,22])
x[:,23]=lb.fit_transform(x[:,23])

In [14]:
x

array([[48.0, 80.0, 1.02, ..., 0, 0, 0],
       [7.0, 50.0, 1.02, ..., 0, 0, 0],
       [62.0, 80.0, 1.01, ..., 1, 0, 1],
       ...,
       [12.0, 80.0, 1.02, ..., 0, 0, 0],
       [17.0, 60.0, 1.025, ..., 0, 0, 0],
       [58.0, 80.0, 1.025, ..., 0, 0, 0]], dtype=object)

In [15]:
x.shape

(400, 24)

In [16]:
y[:,0]=lb.fit_transform(y[:,0])

In [17]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [20]:
x_train

array([[25.0, 60.0, 1.02, ..., 0, 0, 0],
       [55.0, 80.0, 1.01, ..., 0, 0, 0],
       [35.0, 80.0, 1.005, ..., 0, 1, 0],
       ...,
       [51.48337595907928, 70.0, 1.02, ..., 0, 0, 0],
       [11.0, 80.0, 1.01, ..., 0, 0, 0],
       [62.0, 80.0, 1.01, ..., 0, 0, 0]], dtype=object)

In [23]:
x

array([[48.0, 80.0, 1.02, ..., 0, 0, 0],
       [7.0, 50.0, 1.02, ..., 0, 0, 0],
       [62.0, 80.0, 1.01, ..., 1, 0, 1],
       ...,
       [12.0, 80.0, 1.02, ..., 0, 0, 0],
       [17.0, 60.0, 1.025, ..., 0, 0, 0],
       [58.0, 80.0, 1.025, ..., 0, 0, 0]], dtype=object)